"""Builds standalone scripts in dist/ that run without the repo on GitHub:

  dist/kompile.lua            the full hub: main.lua, the UI library, game modules and script list inlined
  dist/kompile-showcase.lua   the UI showcase with the library inlined

Usage: python tools/bundle.py   (rerun after editing anything in src/, games/, scripts/ or examples/)
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"
HEADER = "-- {name}: standalone build. Generated by tools/bundle.py. Don't edit by hand.\n\n"


def read(rel):
    return (ROOT / rel).read_text(encoding="utf-8").rstrip()


def write(name, source):
    DIST.mkdir(exist_ok=True)
    out = DIST / name
    out.write_text(HEADER.format(name=name) + source + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size:,} bytes)")


def build_hub():
    # Every file main.lua can ask for by path, wrapped as a function that returns the file's value.
    files = ["src/ui/Library.lua", "games/registry.lua", "scripts/registry.lua"]
    files += sorted(
        p.relative_to(ROOT).as_posix()
        for p in (ROOT / "games").glob("*.lua")
        if p.name != "registry.lua" and not p.name.startswith("_")
    )
    parts = ["local Modules = {}\n"]
    for rel in files:
        parts.append(f'Modules["{rel}"] = function()\n{read(rel)}\nend\n')
    parts.append(f"local main = (function()\n{read('src/main.lua')}\nend)()\n")
    parts.append("main({ Modules = Modules })")
    write("kompile.lua", "\n".join(parts))


def build_showcase():
    inline = "local Library = (function()\n" + read("src/ui/Library.lua") + "\nend)()"
    showcase = read("examples/showcase.lua")
    bundled, count = re.subn(r"^--#library-start.*?^--#library-end$", lambda _: inline, showcase, count=1, flags=re.M | re.S)
    if count != 1:
        raise SystemExit("Couldn't find the --#library-start/--#library-end block in examples/showcase.lua")
    write("kompile-showcase.lua", bundled)


build_hub()
build_showcase()
